const Head: React.FC = () => {
  return (
    <>
      <title>Cơm Cơm</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://apis.google.com" />
    </>
  );
};

export default Head;
